### ISSUE TITLE
Problem with Faker Number Generator

### ISSUE THREAD

**Issue by mfeinLearn** [learn-co-curriculum/using-to-json-lab#9]
Error:   **1) invoices_index_view renders the invoice partial
     Failure/Error: Product.create(:name => products.sample, :price => Faker::Number.between(1,1500))
     ArgumentError:
       wrong number of arguments (given 2, expected 0)** 

**Previous**: 
     Product.create(:name => products.sample, :price => Faker::Number.between(1,1500))

**Fix**: 
      Product.create(:name => products.sample, :price => Faker::Number.between(from: 1,to: 1500))

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
